import { Project } from "../entities/Project";
import { Company } from "../entities/Company";
import { Department } from "../entities/Department";

export type RegisterUserInfo = {
	first_name: string;
	last_name: string;
	email: string;
	password: string;
	phone_number: string;
};
export type CreateUserInfo = {
	first_name: string;
	last_name: string;
	email: string;
	business_title?: string;
	address?: string;
	phone_number?: string;
	contract_date?: string;
	contract_ex?: string;
	renewal_of_residence?: string;
	id_number?: string;
	id_ex_date?: string;
	salary_per_month?: string;
	salary_per_hour?: string;
	role?: string;
	sign?: string;
	picture?: string;
	file?: string;
	permissions?: any;
	is_verified?: boolean;
	working_hours?: string;
	shift_start?: string;
	shift_end?: string;
	gender?: string;
	projects: Project[];
	department: Department;
	company: Company;
};
export type UpdateUserInfo = {
	first_name: string;
	last_name: string;
	email: string;
	password: string;
	business_title?: string;
	address?: string;
	phone_number?: string;
	contract_date?: Date;
	contract_ex?: Date;
	renewal_of_residence?: Date;
	id_number?: string;
	id_ex_date?: string;
	salary_per_month?: string;
	salary_per_hour?: string;
	role?: string;
	sign?: string;
	picture?: string;
	file?: string;
	permissions?: any;
	is_verified?: boolean;
	working_hours?: string;
	shift_start?: string;
	shift_end?: string;
	gender?: string;
	projects: Project[];
	departmentId: string;
};
